# Generated by Django 5.1.2 on 2024-10-30 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPesticideInfo',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide')], max_length=50)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfileInfo',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropInfo',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('estimated_yield', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmerprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Grows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cropinfo')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmerprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ManageCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cropinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.fertilizerpesticideinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cropinfo')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmerprofileinfo')),
            ],
        ),
    ]
